CLUSTER_ENV: dev
BAKS_INFOTRYGD_FEED_URL: https://familie-baks-infotrygd-feed.dev.intern.nav.no
VEDTAKSFEED_URL: https://vedtaksfeed.dev.intern.nav.no
STS_DISCOVERY_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
STS_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/token