apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: infotrygd-feed-proxy
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{image}}
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readyness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 256Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://infotrygd-feed-proxy.dev.intern.nav.no
    - https://infotrygd-feed-proxy.dev-fss-pub.nais.io
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvinfotrygd-feed
        mountPath: /var/run/secrets/serviceuser/srvinfotrygd-feed
  azure:
    application:
      enabled: true
      claims:
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: ida
          namespace: traktor
          cluster: prod-fss
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev