apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: infotrygd-feed-proxy
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{image}}
  port: 8087
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 256Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://infotrygd-feed-proxy.intern.nav.no
    - https://infotrygd-feed-proxy.prod-fss-pub.nais.io
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvinfotrygd-feed
        mountPath: /var/run/secrets/serviceuser/srvinfotrygd-feed
  azure:
    application:
      enabled: true
      claims:
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: infotrygd-feed-konsument
          namespace: infotrygd
          cluster: prod-fss
    outbound:
      rules:
        - application: familie-baks-infotrygd-feed
          namespace: teamfamilie
          cluster: prod-gcp
        - application: vedtaksfeed
          namespace: tbd
          cluster: prod-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod