name: 'Remove Old Images'
on:
  workflow_dispatch:

jobs:
  remove-images:
    name: 'Remove old images'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'infotrygd-feed-proxy'
          package-type: 'container'
          min-versions-to-keep: 1
